name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo $NAME"

  second_jobs:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo segundo"
