name: Deploy to server

on: 
  push:
    branches:
      - main

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  second_jobs:
  needs: first_jobs
  runs-on: ubuntu-latest

  steps:
    - name: Hola Mundo
      run: echo "Hola Mundo segundo"